// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HdEditorCodeLangSelect: typeof import('./../components/editor/hdEditorCodeLangSelect.vue')['default']
    HdEditorContext: typeof import('./../components/editor/hdEditorContext.vue')['default']
    HdEditorDropCursor: typeof import('./../components/editor/hdEditorDropCursor.vue')['default']
    HdEditorFloatMenu: typeof import('./../components/editor/hdEditorFloatMenu.vue')['default']
    HdEditorHeadingsSubMenu: typeof import('./../components/editor/hdEditorHeadingsSubMenu.vue')['default']
    HdEditorInputFastpath: typeof import('./../components/editor/hdEditorInputFastpath.vue')['default']
    HdEditorLangSelect: typeof import('./../components/editor/hdEditorLangSelect.vue')['default']
    HdEditorLinkEdit: typeof import('./../components/editor/hdEditorLinkEdit.vue')['default']
    HdEditorMenuBasics: typeof import('./../components/editor/hdEditorMenuBasics.vue')['default']
    HdEditorMenuTextAlign: typeof import('./../components/editor/hdEditorMenuTextAlign.vue')['default']
    HdEditorSideTool: typeof import('./../components/editor/hdEditorSideTool.vue')['default']
    HdFontFancyPicker: typeof import('./../components/editor/hdFontFancyPicker.vue')['default']
    HdPageHeader: typeof import('./../components/layouts/hdPageHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
