// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HdEditorContext: typeof import('./../components/editor/hdEditorContext.vue')['default']
    HdEditorHeadingsSubMenu: typeof import('./../components/editor/hdEditorHeadingsSubMenu.vue')['default']
    HdEditorInputFastpath: typeof import('./../components/editor/hdEditorInputFastpath.vue')['default']
    HdEditorLangSelect: typeof import('./../components/editor/hdEditorLangSelect.vue')['default']
    HdEditorLinkEdit: typeof import('./../components/editor/hdEditorLinkEdit.vue')['default']
    HdEditorMenuBasics: typeof import('./../components/editor/hdEditorMenuBasics.vue')['default']
    HdEditorMenuTextAlign: typeof import('./../components/editor/hdEditorMenuTextAlign.vue')['default']
    HdEditorSideTool: typeof import('./../components/editor/hdEditorSideTool.vue')['default']
    HdFloatMenu: typeof import('./../components/editor/hdFloatMenu.vue')['default']
    HdFontFancyPicker: typeof import('./../components/editor/hdFontFancyPicker.vue')['default']
    HdPageHeader: typeof import('./../components/layouts/hdPageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
